### ISSUE TITLE
Bahasa Indonesia Bug (Stemmer Error)

### ISSUE THREAD

**Issue by todiadiyatmo** [10up/ElasticPress#1734]
**Describe the bug**

I have error on elasticpress server log showing that the Indonesian class stemmer not found 

**Steps to Reproduce**
1. Go to setting -> set `Elasticsearch Language` to `Bahasa Indonesia` 
2. Sync via wp-cli
3. Check log on `/var/log/elasticsearch/{index-name}.log`

```
java.lang.IllegalArgumentException: Invalid stemmer class specified: Indonesian
	at org.apache.lucene.analysis.snowball.SnowballFilter.<init>(SnowballFilter.java:83) ~[lucene-analyzers-common-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:33]
	at org.elasticsearch.analysis.common.SnowballTokenFilterFactory.create(SnowballTokenFilterFactory.java:44) ~[?:?]
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:92) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
	at org.apache.lucene.document.Field.tokenStream(Field.java:513) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]

```

**Expected behavior**
Should be able to index with indonesian stemmer, it is supported on the elasticsearch : https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html

**Environment information**

WordPress 5.4
Elasticsearch version : 7.5.1
Elasticpress version : 3.4.1

**Other notes**

Changing the language to English solve the problem
but that mean we use English stemmer for Indonesian Language

**Comment by felipeelia** [comment]
Probably related to #1721

**Comment by tlovett1** [comment]
@todiadiyatmo can you see if #1756  fixes your problem?
