### ISSUE TITLE
BUG: Segfault virtual_file_ex

### ISSUE THREAD

**Issue by jordantrizz** [10up/ElasticPress#4054]
### Describe the bug

Running `wp elasticpress sync --setup` results in a segmentation fault.

```
❯ wp elasticpress sync --setup --force
Syncing with the --setup option will delete your existing index in Elasticsearch. Are you sure you want to delete your Elasticsearch index [y/n] y
Are you sure you want to stop any other ongoing sync? [y/n] y
Sync cleared.
Success: Indexing posts…
Success: Mapping sent
Processed posts 0 - 50 of 2970. Last Object ID: 162493
Processed posts 50 - 100 of 2970. Last Object ID: 158180
Processed posts 100 - 150 of 2970. Last Object ID: 144470
Processed posts 150 - 200 of 2970. Last Object ID: 135884
Processed posts 200 - 250 of 2970. Last Object ID: 127129
Processed posts 250 - 300 of 2970. Last Object ID: 117744
Processed posts 300 - 350 of 2970. Last Object ID: 109343
Processed posts 350 - 400 of 2970. Last Object ID: 88910
Processed posts 400 - 450 of 2970. Last Object ID: 73605
Processed posts 450 - 500 of 2970. Last Object ID: 66332
Time elapsed: 00:00:03.330000
Memory Usage: 125.93mb (Peak: 128.64mb)
Processed posts 500 - 550 of 2970. Last Object ID: 63042
Processed posts 550 - 600 of 2970. Last Object ID: 56616
Processed posts 600 - 650 of 2970. Last Object ID: 46141
Processed posts 650 - 700 of 2970. Last Object ID: 44952
Processed posts 700 - 750 of 2970. Last Object ID: 44415
Processed posts 750 - 800 of 2970. Last Object ID: 43904
Processed posts 800 - 850 of 2970. Last Object ID: 43110
Processed posts 850 - 900 of 2970. Last Object ID: 42558
Processed posts 900 - 950 of 2970. Last Object ID: 41710
Processed posts 950 - 1000 of 2970. Last Object ID: 41148
Time elapsed: 00:00:06.660000 (+3.325)
Memory Usage: 126.25mb (Peak: 131.59mb)
Processed posts 1000 - 1050 of 2970. Last Object ID: 40659
Processed posts 1050 - 1100 of 2970. Last Object ID: 40252
Processed posts 1100 - 1150 of 2970. Last Object ID: 39410
Processed posts 1150 - 1200 of 2970. Last Object ID: 38936
Processed posts 1200 - 1250 of 2970. Last Object ID: 38290
Processed posts 1250 - 1300 of 2970. Last Object ID: 37259
Processed posts 1300 - 1350 of 2970. Last Object ID: 36302
Processed posts 1350 - 1400 of 2970. Last Object ID: 35421
Processed posts 1400 - 1450 of 2970. Last Object ID: 34407
Processed posts 1450 - 1500 of 2970. Last Object ID: 33556
Time elapsed: 00:00:09.550000 (+2.886)
Memory Usage: 125.2mb (Peak: 131.88mb)
Processed posts 1500 - 1550 of 2970. Last Object ID: 32784
Processed posts 1550 - 1600 of 2970. Last Object ID: 31813
Processed posts 1600 - 1650 of 2970. Last Object ID: 30538
Processed posts 1650 - 1700 of 2970. Last Object ID: 28953
Processed posts 1700 - 1750 of 2970. Last Object ID: 27764
Processed posts 1750 - 1800 of 2970. Last Object ID: 18545
Processed posts 1800 - 1850 of 2970. Last Object ID: 17857
Processed posts 1850 - 1900 of 2970. Last Object ID: 16643
Processed posts 1900 - 1950 of 2970. Last Object ID: 15652
Processed posts 1950 - 2000 of 2970. Last Object ID: 14714
Time elapsed: 00:00:12.710000 (+3.164)
Memory Usage: 130.57mb (Peak: 135.88mb)
[1]    1069336 segmentation fault (core dumped)  wp --allow-root elasticpress sync --setup --force
```

### Steps to Reproduce

Run `wp elasticpress sync --setup`

### Screenshots, screen recording, code snippet

```
#0  0x000055e9e15dfae5 in virtual_file_ex ()
(gdb) bt
#0  0x000055e9e15dfae5 in virtual_file_ex ()
#1  0x000055e9e14f74c9 in expand_filepath_with_mode ()
#2  0x000055e9e150e261 in _php_stream_fopen ()
#3  0x000055e9e1509631 in _php_stream_open_wrapper_ex ()
#4  0x000055e9e14923cf in ?? ()
#5  0x00007fbaebd03dcc in ?? () from /usr/lib/php/20210902/phar.so
#6  0x000055e9e15c2c63 in execute_ex ()
#7  0x000055e9e1549414 in zend_call_function ()
#8  0x000055e9e13e688a in ?? ()
#9  0x000055e9e13e793c in ?? ()
#10 0x000055e9e13e7bc1 in ?? ()
#11 0x000055e9e13e7f7a in ?? ()
#12 0x000055e9e15c2c63 in execute_ex ()
#13 0x000055e9e1549414 in zend_call_function ()
#14 0x000055e9e1484813 in ?? ()
#15 0x000055e9e15c592b in execute_ex ()
#16 0x000055e9e1549414 in zend_call_function ()
#17 0x000055e9e13e688a in ?? ()
#18 0x000055e9e13e793c in ?? ()
#19 0x000055e9e13e7bc1 in ?? ()
#20 0x000055e9e13e7f7a in ?? ()
#21 0x000055e9e15c2c63 in execute_ex ()
#22 0x000055e9e1549414 in zend_call_function ()
#23 0x000055e9e1484813 in ?? ()
#24 0x000055e9e15c592b in execute_ex ()
#25 0x000055e9e1549414 in zend_call_function ()
#26 0x000055e9e13e688a in ?? ()
#27 0x000055e9e13e793c in ?? ()
#28 0x000055e9e13e7bc1 in ?? ()
#29 0x000055e9e13e7f7a in ?? ()
#30 0x000055e9e15c2c63 in execute_ex ()
#31 0x000055e9e1549414 in zend_call_function ()
#32 0x000055e9e1484813 in ?? ()
#33 0x000055e9e15c592b in execute_ex ()
#34 0x000055e9e1549414 in zend_call_function ()
#35 0x000055e9e13e688a in ?? ()
#36 0x000055e9e13e793c in ?? ()
#37 0x000055e9e13e7bc1 in ?? ()
#38 0x000055e9e13e7f7a in ?? ()
#39 0x000055e9e15c2c63 in execute_ex ()
#40 0x000055e9e1549414 in zend_call_function ()
#41 0x000055e9e1484813 in ?? ()
#42 0x000055e9e15c592b in execute_ex ()
#43 0x000055e9e1549414 in zend_call_function ()
#44 0x000055e9e13e688a in ?? ()
#45 0x000055e9e13e793c in ?? ()
#46 0x000055e9e13e7bc1 in ?? ()
#47 0x000055e9e13e7f7a in ?? ()
#48 0x000055e9e15c2c63 in execute_ex ()
#49 0x000055e9e1549414 in zend_call_function ()
#50 0x000055e9e1484813 in ?? ()
#51 0x000055e9e15c592b in execute_ex ()
#52 0x000055e9e1549414 in zend_call_function ()
#53 0x000055e9e13e688a in ?? ()
#54 0x000055e9e13e793c in ?? ()
#55 0x000055e9e13e7bc1 in ?? ()
```

### Environment information

wp-cli

```
❯ wp cli info                                                                                                                                                                        ░▒▓ 15.204.142.119   
OS:     Linux 5.15.0-127-generic #137-Ubuntu SMP Fri Nov 8 15:21:01 UTC 2024 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.1
PHP version:    8.1.31
php.ini used:   /etc/php/8.1/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 8.0.39-30 for Linux on x86_64 (Percona Server (GPL), Release '30', Revision '41ebc5d9')
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       <removed>
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.11.0
```

### WordPress and ElasticPress information

```
## Failed Queries ##



## WordPress ##

### WordPress Environment ###
wp_version: 6.7.1
is_multisite: false
theme: PTST Theme (1.1)
parent_theme: Bricks (1.11.1.1)
plugins: Accessibility Checker (1.16.4), Anti-Spam by CleanTalk (6.47), Author Filters (3.5.6), Automatic.css (3.2.9), Classic Editor (1.6.7), CommandUI (1.0.0-rc.6), ElasticPress (5.1.4), Featured Images in RSS for Mailchimp & More (1.6.3), FluentSMTP (2.2.83), FooBox Image Lightbox (2.7.33), FooGallery (2.4.27), Imagify (2.2.3.2), MC4WP: Mailchimp for WordPress (4.9.20), Microsoft Clarity (0.10.3), Nginx Helper (2.2.6), Raptive Ads (3.6.2), Really Simple Featured Video (0.17.0), SEOPress (8.4.1), SEOPress PRO (8.4), TablePress (3.0.1), WP fail2ban (5.3.4), WPMU DEV Dashboard (4.11.28), WP Rocket (3.17.3.1), WP Simple Shopping Cart (5.0.8), WP Umbrella (2.17.1), WS Form PRO (1.9.245), and XFtoWP (1.6)
revisions: all

### Server Environment ###
php_version: 8.2.26
memory_limit: 2048M
timeout: 600

## Indexable Content ##

### Site
post_count: 2,942
page_count: 16
wpsc_cart_orders_count: 17
bricks_template_count: 12
post_meta_keys: 0
page_meta_keys: 0
wpsc_cart_orders_meta_keys: 0
bricks_template_meta_keys: 0
total-all-post-types: 0
distinct-meta-keys: 



## ElasticPress ##

### Settings ###
host: http://localhost:9200
index_prefix: 
language: site-default
per_page: 10
network_active: false

### Timeouts ###
request_timeout: 5
index_document_timeout: 15
bulk_request_timeout: 30



## Elasticsearch Indices ##

### post-1 ###
health: yellow
status: open
index: post-1
uuid: pIen8rt4TmiIMvWxWeDdtg
pri: 5
rep: 1
docs.count: 2000
docs.deleted: 0
store.size: 61.8mb
pri.store.size: 61.8mb
total_fields_limit: 5000
analyzer_language: english
stop_language: _english_
snowball_language: English



## Last Sync ##

### 2024/12/21 8:13:34 am ###
method: WP-CLI
is_full_sync: Yes
end_date_time: 2024/12/21 8:17:41 am
total_time: 0 hours, 4 minutes, 7 seconds
total: 0
synced: 0
skipped: 0
failed: 0
errors: array (
)
trigger: 
final_status: aborted



## Feature Settings ##

### Autosuggest ###
active: true
autosuggest_selector: input[type="search"]
endpoint_url: https://domain.com/ep-autosuggest
force_inactive: false
trigger_ga_event: 0

### Custom Search Results ###
active: true
force_inactive: false

### Did You Mean ###
active: true
force_inactive: false
search_behavior: 0

### Filters ###
active: true
force_inactive: false
match_type: all

### Post Search ###
active: true
decaying_enabled: 1
force_inactive: false
highlight_enabled: 1
highlight_excerpt: 0
highlight_tag: span
synonyms_editor_mode: simple
synonyms: <pre># Defined synonyms.
runner, running shoe, sneaker, tennis shoe, trainer

# Defined hyponyms.
blue => blue, aqua, azure, cerulean, cyan, ultramarine

# Defined replacements.
supposably => supposedly
flustrated => flustered, frustrated
intensive purposes => intents and purposes</pre>
weighting: array (
  'post' => 
  array (
    'post_title' => 
    array (
      'enabled' => true,
      'weight' => 80,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => true,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.post_tag.name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.category.name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
  'page' => 
  array (
    'post_title' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_content' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'post_excerpt' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'author_name' => 
    array (
      'weight' => 1,
      'enabled' => false,
    ),
    'terms.ep_custom_result.name' => 
    array (
      'enabled' => true,
      'weight' => 9999,
      'fuzziness' => false,
    ),
  ),
)

### Related Posts ###
active: true
force_inactive: false

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Usually, segfault errors happen in a much lower layer of code than a WordPress plugin. I recommend you update your PHP version and try again.

**Comment by jordantrizz** [comment]
Thanks, Ubuntu 24 PHP 8.1-4 have the same segfault.
